[2022-06-27 13:30:39,137] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.accurate scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-06-27 13:30:39,164] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.accurate scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-06-27 13:30:39,167] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:30:39,169] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:30:39,171] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:30:39,297] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): accurate> on 2022-01-10 00:00:00+00:00
[2022-06-27 13:30:39,359] {standard_task_runner.py:52} INFO - Started process 56784 to run task
[2022-06-27 13:30:39,373] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'accurate', 'scheduled__2022-01-10T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp3hro1rca', '--error-file', '/tmp/tmpa4x_ot7y']
[2022-06-27 13:30:39,390] {standard_task_runner.py:80} INFO - Job 92: Subtask accurate
[2022-06-27 13:30:39,619] {task_command.py:370} INFO - Running <TaskInstance: dag1.accurate scheduled__2022-01-10T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:30:39,791] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-01-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-10T00:00:00+00:00
[2022-06-27 13:30:39,793] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:30:39,795] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-06-27 13:30:39,828] {subprocess.py:85} INFO - Output:
[2022-06-27 13:30:39,831] {subprocess.py:92} INFO - accurate
[2022-06-27 13:30:39,833] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:30:39,879] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=accurate, execution_date=20220110T000000, start_date=20220627T133039, end_date=20220627T133039
[2022-06-27 13:30:39,934] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:30:39,966] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
